/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Service.AdminDataRequest;
import Service.AdminService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyangiprasad
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public static String unallocatedTableName = "unallocatedRequests";
    public static String investigationTableName = "investigationRequests";
    public static String medicalTableName = "medicalRequests";
    public static String lawTableName = "lawRequests";
    
//    public Admin() {
//        initComponents();
//        btnAssign.setVisible(true);
//        btnAdminAccept.setVisible(true);
//        btnAdminReject.setVisible(true);
//    }

    Admin(String email, String password) {
        initComponents();
        btnAssign.setVisible(true);
        btnAdminAccept.setVisible(true);
        btnAdminReject.setVisible(true);
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminFull = new javax.swing.JPanel();
        btnLawData = new javax.swing.JButton();
        btnUnallocatedRequest = new javax.swing.JButton();
        btnHospitalData = new javax.swing.JButton();
        btnInvestigationData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminPopulateData = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnAdminAccept = new javax.swing.JButton();
        btnAdminReject = new javax.swing.JButton();
        lblAdminPic = new javax.swing.JLabel();
        lblCloseAdmin = new javax.swing.JLabel();
        lblCreateTitle = new javax.swing.JLabel();
        lblAdminLogout = new javax.swing.JLabel();
        TFAdminRequestId = new javax.swing.JTextField();
        CBAdmin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAdminFull.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminFull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLawData.setBackground(new java.awt.Color(255, 153, 51));
        btnLawData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLawData.setText("Law Enterprise Data");
        btnLawData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawDataActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnLawData, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 240, 40));

        btnUnallocatedRequest.setBackground(new java.awt.Color(255, 153, 51));
        btnUnallocatedRequest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnallocatedRequest.setText("Unallocated Requests");
        btnUnallocatedRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnallocatedRequestActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnUnallocatedRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 40));

        btnHospitalData.setBackground(new java.awt.Color(255, 153, 51));
        btnHospitalData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHospitalData.setText("Hospital Enterprise Data");
        btnHospitalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalDataActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnHospitalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 230, 40));

        btnInvestigationData.setBackground(new java.awt.Color(255, 153, 51));
        btnInvestigationData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInvestigationData.setText("Investigation Enterprise Data");
        btnInvestigationData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestigationDataActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnInvestigationData, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 260, 40));

        tblAdminPopulateData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Victim Name", "Department", "Assigned To", "Status"
            }
        ));
        tblAdminPopulateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminPopulateDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdminPopulateData);

        pnlAdminFull.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 1150, 270));

        btnAssign.setBackground(new java.awt.Color(68, 168, 217));
        btnAssign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 140, 40));

        btnAdminAccept.setBackground(new java.awt.Color(68, 168, 217));
        btnAdminAccept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdminAccept.setText("Accept");
        btnAdminAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAcceptActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnAdminAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 150, 40));

        btnAdminReject.setBackground(new java.awt.Color(68, 168, 217));
        btnAdminReject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdminReject.setText("Reject");
        btnAdminReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminRejectActionPerformed(evt);
            }
        });
        pnlAdminFull.add(btnAdminReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 690, 150, 40));

        lblAdminPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/raisevoice.jpg"))); // NOI18N
        pnlAdminFull.add(lblAdminPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 510, 410, 290));

        lblCloseAdmin.setBackground(new java.awt.Color(68, 168, 217));
        lblCloseAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCloseAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblCloseAdmin.setText("X");
        lblCloseAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseAdminMouseClicked(evt);
            }
        });
        pnlAdminFull.add(lblCloseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 0, 20, 20));

        lblCreateTitle.setBackground(new java.awt.Color(68, 168, 217));
        lblCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("ADMINISTRATION");
        lblCreateTitle.setOpaque(true);
        pnlAdminFull.add(lblCreateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 60));

        lblAdminLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAdminLogout.setForeground(new java.awt.Color(0, 51, 102));
        lblAdminLogout.setText("Logout");
        lblAdminLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminLogoutMouseClicked(evt);
            }
        });
        pnlAdminFull.add(lblAdminLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 60, 70, 20));

        TFAdminRequestId.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        TFAdminRequestId.setForeground(new java.awt.Color(102, 102, 102));
        TFAdminRequestId.setText("Request ID...");
        TFAdminRequestId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        TFAdminRequestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAdminRequestIdActionPerformed(evt);
            }
        });
        pnlAdminFull.add(TFAdminRequestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 220, 40));

        CBAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital Enterprise", "Investigation Enterprise" }));
        CBAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAdminActionPerformed(evt);
            }
        });
        pnlAdminFull.add(CBAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 330, 40));

        getContentPane().add(pnlAdminFull, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLawDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawDataActionPerformed
        populateTable(lawTableName);
    }//GEN-LAST:event_btnLawDataActionPerformed

    private void btnHospitalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalDataActionPerformed
        populateTable(medicalTableName);
    }//GEN-LAST:event_btnHospitalDataActionPerformed

    private void btnInvestigationDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvestigationDataActionPerformed
        populateTable(investigationTableName);
    }//GEN-LAST:event_btnInvestigationDataActionPerformed

    private void btnUnallocatedRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnallocatedRequestActionPerformed
        populateTable(unallocatedTableName);
        
    }//GEN-LAST:event_btnUnallocatedRequestActionPerformed

    private void tblAdminPopulateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminPopulateDataMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) tblAdminPopulateData.getModel();
        int selectedRowIndex = tblAdminPopulateData.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        /*
        on selection check status and display relevant buttons
        assignToHospitalBtn.setVisible(true);
        assignToInvestigationBtn.setVisible(true);
        assignToLawBtn.setVisible(true);
        */
    }//GEN-LAST:event_tblAdminPopulateDataMouseClicked

    private void btnAdminAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAcceptActionPerformed
        
        //accept request and send to counselling or investigation department
        DefaultTableModel model = (DefaultTableModel) tblAdminPopulateData.getModel();
        int selectedRowIndex = tblAdminPopulateData.getSelectedRow();
        
        if(selectedRowIndex < 0 )
        {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        String requestId = String.valueOf(model.getValueAt(selectedRowIndex, 0));
        String enterprise = String.valueOf(CBAdmin.getSelectedItem());
        Boolean response = false;
        AdminService adminService = new AdminService();
        
        switch(enterprise)
        {
            case "Hospital Enterprise":
                response = adminService.assignCaseToHospital(requestId);
                break;
            case "Investigation Enterprise":
                response = adminService.assignCaseToInvestigation(requestId);
                break;
        }
        if(response == false)
        {
            JOptionPane.showMessageDialog(null, "Successfully rejected case");
        }
    }//GEN-LAST:event_btnAdminAcceptActionPerformed

    private void lblCloseAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseAdminMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseAdminMouseClicked

    private void lblAdminLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminLogoutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Successfully Logout");
        new HomePage().setVisible(true);
    }//GEN-LAST:event_lblAdminLogoutMouseClicked

    private void TFAdminRequestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAdminRequestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAdminRequestIdActionPerformed

    private void CBAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBAdminActionPerformed

    private void btnAdminRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminRejectActionPerformed
        
        String tableName = "";
        
        DefaultTableModel model = (DefaultTableModel) tblAdminPopulateData.getModel();
        int selectedRowIndex = tblAdminPopulateData.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to Reject this case?");
        // 0=yes, 1=no, 2=cancel
        System.out.println(i);
        AdminService adminService = new AdminService();
        if(i==0)
        {
            String requestId = String.valueOf(model.getValueAt(selectedRowIndex, 0));
            Boolean r = adminService.rejectCase(tableName, requestId);
            if(r)
                JOptionPane.showMessageDialog(null, "Successfully rejected case");
        }
        return;
    }//GEN-LAST:event_btnAdminRejectActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblAdminPopulateData.getModel();
        int selectedRowIndex = tblAdminPopulateData.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
    }//GEN-LAST:event_btnAssignActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBAdmin;
    private javax.swing.JTextField TFAdminRequestId;
    private javax.swing.JButton btnAdminAccept;
    private javax.swing.JButton btnAdminReject;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnHospitalData;
    private javax.swing.JButton btnInvestigationData;
    private javax.swing.JButton btnLawData;
    private javax.swing.JButton btnUnallocatedRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminLogout;
    private javax.swing.JLabel lblAdminPic;
    private javax.swing.JLabel lblCloseAdmin;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JPanel pnlAdminFull;
    private javax.swing.JTable tblAdminPopulateData;
    // End of variables declaration//GEN-END:variables

    private void populateTable(String tableName) {
        DefaultTableModel model = (DefaultTableModel) tblAdminPopulateData.getModel();
        model.setRowCount(0);
        int i = 1;
        /*
        call table with relelvant details
        
        */
        AdminService adminService = new AdminService();
        ArrayList<AdminDataRequest> result = new ArrayList<>();
        
        result = tableName.equals("unallocatedRequests") ? adminService.getAdminRequests() : adminService.getRequests(tableName, false);
        if(result == null)
        {
            JOptionPane.showMessageDialog(null, "No Data Available");
            return;
        }
        System.out.println(result.size());
       
        for(AdminDataRequest r: result)
        {
            Object[] row = new Object[11];
            row[0] = r.getRequestId();
            row[1] = r.getVictimEmail();
            row[2] = r.getDepartment();
            row[3] = r.getAssigned_To();
            row[4] = r.getStatus();
            
            model.addRow(row);
        }
    }
}
