/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Service.RecoverPassword;
import javax.swing.JOptionPane;

/**
 *
 * @author mahak
 */
public class GetPassword extends javax.swing.JFrame {
    RecoverPassword recoverPass;
    String pass;
    /**
     * Creates new form GetPassword
     */
    public GetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForgotPswd = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblPetName = new javax.swing.JLabel();
        CBRole = new javax.swing.JComboBox<>();
        TFPetName = new javax.swing.JTextField();
        TFEmail = new javax.swing.JTextField();
        btnRecoverPswd = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblBackPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlForgotPswd.setBackground(new java.awt.Color(255, 255, 255));
        pnlForgotPswd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");
        pnlForgotPswd.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 30));

        lblPetName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPetName.setText(" Pet's Name:");
        pnlForgotPswd.add(lblPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 28));

        CBRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Victim", "Staff" }));
        pnlForgotPswd.add(CBRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 213, 36));
        pnlForgotPswd.add(TFPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, 38));
        pnlForgotPswd.add(TFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 38));

        btnRecoverPswd.setBackground(new java.awt.Color(255, 255, 255));
        btnRecoverPswd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRecoverPswd.setText("Recover Password");
        btnRecoverPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoverPswdActionPerformed(evt);
            }
        });
        pnlForgotPswd.add(btnRecoverPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 50));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlForgotPswd.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 10, 20));

        lblBackPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Pet.jpg"))); // NOI18N
        pnlForgotPswd.add(lblBackPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlForgotPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlForgotPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(680, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnRecoverPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoverPswdActionPerformed
        // TODO add your handling code here: 
        try
        {   
          
            if(TFEmail.getText().isEmpty())
            {
                 throw new Exception("Add Email"); 
            }
            else if(TFPetName.getText().isEmpty()){
                     throw new Exception("Add pet name"); 
             }
            else if(CBRole.getSelectedItem().toString()=="Select"){
                     throw new Exception("Select User"); 
             }
            
            else{   recoverPass = new RecoverPassword();
           pass = recoverPass.ReturnPassword(TFEmail.getText(), TFPetName.getText(), CBRole.getSelectedItem().toString());
                    JOptionPane.showMessageDialog(null,"Your passwors is - "+pass);
                   }
                    

        }
          catch(Exception e)
        {
          
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
          
       
    }//GEN-LAST:event_btnRecoverPswdActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GetPassword().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBRole;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFPetName;
    private javax.swing.JButton btnRecoverPswd;
    private javax.swing.JLabel lblBackPic;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JPanel pnlForgotPswd;
    // End of variables declaration//GEN-END:variables
}
