/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Service.Staff;
import Service.StaffRegistration;
import Service.Victim;
import Service.VictimRegistration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author mahak
 */
public class MainRegister extends javax.swing.JFrame {

    /**
     * Creates new form MainRegister
     */
    VictimRegistration vicReg;
    Victim vic;
    Staff staff;
    StaffRegistration staffreg;
     String regex = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$";  
     Pattern pattern = Pattern.compile(regex);  
     
       
    public MainRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlMainReg = new javax.swing.JPanel();
        pnlLeftReg = new javax.swing.JPanel();
        btnVictimReg = new javax.swing.JButton();
        btnStaffReg = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pnlTopReg = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlTabFirst = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlTabVictimReg = new javax.swing.JPanel();
        objTFName = new javax.swing.JTextField();
        objTFCNo = new javax.swing.JTextField();
        objTFEmail = new javax.swing.JTextField();
        objPFpassword = new javax.swing.JPasswordField();
        btnTabVicReg = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        objTFPetName2 = new javax.swing.JTextField();
        CBTabVictimCity = new javax.swing.JComboBox<>();
        pnlTabStaffReg = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        objTFName1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        objTFCNo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        objTFEmail1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CBTabStaffCity = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        CBTabStaffDept = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        CBTabStaffRole = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        objTFPetName1 = new javax.swing.JTextField();
        btnTabStaffReg = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        objPFpassword2 = new javax.swing.JPasswordField();
        CBTabStaffEnt = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainReg.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeftReg.setBackground(new java.awt.Color(68, 168, 217));
        pnlLeftReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVictimReg.setBackground(new java.awt.Color(255, 255, 255));
        btnVictimReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVictimReg.setText("Register For Victim");
        btnVictimReg.setBorder(null);
        btnVictimReg.setBorderPainted(false);
        btnVictimReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVictimRegActionPerformed(evt);
            }
        });
        pnlLeftReg.add(btnVictimReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 237, 87));

        btnStaffReg.setBackground(new java.awt.Color(255, 255, 255));
        btnStaffReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStaffReg.setText("Register For Staff");
        btnStaffReg.setBorder(null);
        btnStaffReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffRegActionPerformed(evt);
            }
        });
        pnlLeftReg.add(btnStaffReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 313, 237, 87));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/BACK.jpg"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLeftReg.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        pnlMainReg.add(pnlLeftReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 850));

        pnlTopReg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LET IT OUT!");

        javax.swing.GroupLayout pnlTopRegLayout = new javax.swing.GroupLayout(pnlTopReg);
        pnlTopReg.setLayout(pnlTopRegLayout);
        pnlTopRegLayout.setHorizontalGroup(
            pnlTopRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopRegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTopRegLayout.setVerticalGroup(
            pnlTopRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopRegLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMainReg.add(pnlTopReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 600, 90));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        pnlTabFirst.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/voice7.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlTabFirstLayout = new javax.swing.GroupLayout(pnlTabFirst);
        pnlTabFirst.setLayout(pnlTabFirstLayout);
        pnlTabFirstLayout.setHorizontalGroup(
            pnlTabFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabFirstLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel14)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        pnlTabFirstLayout.setVerticalGroup(
            pnlTabFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabFirstLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel14)
                .addContainerGap(436, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", pnlTabFirst);

        pnlTabVictimReg.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabVictimReg.setLayout(null);
        pnlTabVictimReg.add(objTFName);
        objTFName.setBounds(371, 40, 224, 35);
        pnlTabVictimReg.add(objTFCNo);
        objTFCNo.setBounds(371, 100, 224, 35);
        pnlTabVictimReg.add(objTFEmail);
        objTFEmail.setBounds(371, 160, 224, 35);

        objPFpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objPFpasswordActionPerformed(evt);
            }
        });
        pnlTabVictimReg.add(objPFpassword);
        objPFpassword.setBounds(371, 220, 224, 35);

        btnTabVicReg.setBackground(new java.awt.Color(255, 153, 51));
        btnTabVicReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTabVicReg.setText("REGISTER");
        btnTabVicReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTabVicReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabVicRegActionPerformed(evt);
            }
        });
        pnlTabVictimReg.add(btnTabVicReg);
        btnTabVicReg.setBounds(300, 420, 125, 43);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Security Question:What's your pet name:");
        jLabel16.setOpaque(true);
        pnlTabVictimReg.add(jLabel16);
        jLabel16.setBounds(30, 340, 320, 35);
        jLabel16.getAccessibleContext().setAccessibleName("Name");
        jLabel16.getAccessibleContext().setAccessibleDescription("");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Name:");
        jLabel17.setOpaque(true);
        pnlTabVictimReg.add(jLabel17);
        jLabel17.setBounds(120, 40, 224, 35);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Contact No:");
        jLabel18.setOpaque(true);
        pnlTabVictimReg.add(jLabel18);
        jLabel18.setBounds(120, 100, 224, 35);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("City:");
        jLabel19.setOpaque(true);
        pnlTabVictimReg.add(jLabel19);
        jLabel19.setBounds(120, 280, 224, 35);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Email Id:");
        jLabel20.setOpaque(true);
        pnlTabVictimReg.add(jLabel20);
        jLabel20.setBounds(120, 160, 224, 35);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Password:");
        jLabel21.setOpaque(true);
        pnlTabVictimReg.add(jLabel21);
        jLabel21.setBounds(120, 220, 224, 35);
        pnlTabVictimReg.add(objTFPetName2);
        objTFPetName2.setBounds(370, 340, 224, 35);

        CBTabVictimCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Boston", "" }));
        pnlTabVictimReg.add(CBTabVictimCity);
        CBTabVictimCity.setBounds(370, 280, 224, 35);

        jTabbedPane1.addTab("", pnlTabVictimReg);

        pnlTabStaffReg.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabStaffReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Name:");
        pnlTabStaffReg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 47, 75, 35));
        pnlTabStaffReg.add(objTFName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 49, 224, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Contact No:");
        pnlTabStaffReg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 27));
        pnlTabStaffReg.add(objTFCNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 224, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("City:");
        pnlTabStaffReg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 102, 28));
        pnlTabStaffReg.add(objTFEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 224, 35));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Password:");
        pnlTabStaffReg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 102, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Enterprise:");
        pnlTabStaffReg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 102, 35));

        CBTabStaffCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Boston" }));
        pnlTabStaffReg.add(CBTabStaffCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 224, 35));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Department:");
        pnlTabStaffReg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 102, 35));

        CBTabStaffDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        CBTabStaffDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CBTabStaffDeptMouseExited(evt);
            }
        });
        CBTabStaffDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTabStaffDeptActionPerformed(evt);
            }
        });
        pnlTabStaffReg.add(CBTabStaffDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 224, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Role:");
        pnlTabStaffReg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 79, 35));

        CBTabStaffRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        CBTabStaffRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTabStaffRoleActionPerformed(evt);
            }
        });
        pnlTabStaffReg.add(CBTabStaffRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 224, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Security Question-What is your pet's name:");
        pnlTabStaffReg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, 46));
        pnlTabStaffReg.add(objTFPetName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 224, 35));

        btnTabStaffReg.setBackground(new java.awt.Color(255, 153, 51));
        btnTabStaffReg.setText("REGISTER");
        btnTabStaffReg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTabStaffReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabStaffRegActionPerformed(evt);
            }
        });
        pnlTabStaffReg.add(btnTabStaffReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 608, 138, 38));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Email Id:");
        pnlTabStaffReg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 102, 28));

        objPFpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objPFpassword2ActionPerformed(evt);
            }
        });
        pnlTabStaffReg.add(objPFpassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 224, 35));

        CBTabStaffEnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Hospital", "Investigation", "Justice", "Raise Your Voice" }));
        CBTabStaffEnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBTabStaffEntMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CBTabStaffEntMouseExited(evt);
            }
        });
        pnlTabStaffReg.add(CBTabStaffEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 224, 35));

        jTabbedPane1.addTab("", pnlTabStaffReg);

        pnlMainReg.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 670, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainReg, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1537, 943));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVictimRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVictimRegActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnVictimRegActionPerformed

    private void objPFpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objPFpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_objPFpasswordActionPerformed

    private void CBTabStaffDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTabStaffDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTabStaffDeptActionPerformed

    private void CBTabStaffRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTabStaffRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTabStaffRoleActionPerformed

    private void btnTabStaffRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabStaffRegActionPerformed
        // TODO add your handling code here:
       try
        {
          
            if(objTFName1.getText().isEmpty())
            {
                 throw new Exception("Add name"); 
            }
            else if(objTFCNo1.getText().isEmpty()){
                     throw new Exception("Add contact number");
            }
            else if(objTFEmail1.getText().isEmpty()){
                     throw new Exception("Add email"); 
            }
            else if(objPFpassword2.getPassword().toString().isEmpty()){
                     throw new Exception("Add password"); 
             }
            else if(CBTabStaffCity.getSelectedItem().toString()=="Select"){
                     throw new Exception("Select City"); 
             }
            else if(CBTabStaffEnt.getSelectedItem().toString()=="Select"){
                     throw new Exception("Select Enterprise"); 
             }
            else if(CBTabStaffDept.getSelectedItem().toString()=="Select"){
                     throw new Exception("Select Department"); 
             }
            else if(CBTabStaffRole.getSelectedItem().toString()=="Select"){
                     throw new Exception("Select Role"); 
             }
            else if(objTFPetName1.getText().isEmpty()){
                     throw new Exception("Add pet name in security question"); 
            }
            else{ 
               // Matcher matcher = pattern.matcher(objTFEmail1.getText());  
             
                if(!(objTFName1.getText().matches("^[a-zA-Z]*$"))){
                 throw new Exception("Name can contain characters only"); 
                }
                
                else if(!(objTFCNo1.getText().matches("^((?!(0))[0-9]{10})$"))){
                 throw new Exception("Enter a valid phone number"); 
                }
                else if(!(objTFEmail1.getText().matches("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$"))){
                 throw new Exception("Enter a valid email"); 
                }
               
                else if(!(String.valueOf(objPFpassword2.getPassword()).matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$"))){
                    System.out.println(String.valueOf(objPFpassword2.getPassword()));
                 throw new Exception("Enter a valid password. A valid password must contain atleast one lowercase,one  uppercase,one  special and one  digit character.And must be of length between 8-20"); 
                }
                else if(!(objTFPetName1.getText().matches("^[a-zA-Z]*$"))){
                 throw new Exception("Enter a valid pet name"); 
                }
                else{
                staff = new Staff();
                staff.setName(objTFName1.getText());
                staff.setContact(Long.parseLong(objTFCNo1.getText()));
                staff.setEmail(objTFEmail1.getText());
                staff.setCity(CBTabStaffCity.getSelectedItem().toString());
                staff.setPassword(String.valueOf(objPFpassword2.getPassword()));
                staff.setEnterprise(CBTabStaffEnt.getSelectedItem().toString());
                staff.setDepartment(CBTabStaffDept.getSelectedItem().toString());
                staff.setRole(CBTabStaffRole.getSelectedItem().toString());
                staff.setSecurity_question(objTFPetName1.getText());
                staff.setWorking_Status("");
                
                
                staffreg = new StaffRegistration(staff);
                
                objTFName1.setText("");
                objTFCNo1.setText("");
                objTFEmail1.setText("");
                CBTabStaffCity.setSelectedItem("Select");
                objPFpassword2.setText("");
                
                CBTabStaffEnt.setSelectedItem("Select");
                CBTabStaffDept.removeAllItems();
                CBTabStaffDept.addItem("Select");
                CBTabStaffRole.removeAllItems();
                CBTabStaffRole.addItem("Select");
                objTFPetName1.setText("");
                
                
                }
            }
            
        }
          catch(Exception e)
        {
          
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
        
    }//GEN-LAST:event_btnTabStaffRegActionPerformed

    private void btnStaffRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffRegActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnStaffRegActionPerformed

    private void objPFpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objPFpassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_objPFpassword2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTabVicRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabVicRegActionPerformed
        // TODO add your handling code here:
         try
        {
          
            if(objTFName.getText().isEmpty())
            {
                 throw new Exception("Add name"); 
            }
            else if(objTFCNo.getText().isEmpty()){
                     throw new Exception("Add contact number");
            }
            else if(objTFEmail.getText().isEmpty()){
                     throw new Exception("Add email"); 
            }
            else if(String.valueOf(objPFpassword.getPassword()).isEmpty()){
                     throw new Exception("Add password"); 
             }
            else if(CBTabVictimCity.getSelectedItem().toString()=="Select"){
                     throw new Exception("Select City"); 
             }
            else if(objTFPetName2.getText().isEmpty()){
                     throw new Exception("Add pet name in security question"); 
            }
            else{
               //   Matcher matcher = pattern.matcher(objTFEmail.getText()); 
                if(!(objTFName.getText().matches("^[a-zA-Z]*$"))){
                 throw new Exception("Name can contain characters only"); 
                }
                
                else if(!(objTFCNo.getText().matches("^((?!(0))[0-9]{10})$"))){
                 throw new Exception("Enter a valid phone number"); 
                }
                else if(!(objTFEmail.getText().matches("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$"))){
                 throw new Exception("Enter a valid email"); 
                }
                else if(!(String.valueOf(objPFpassword.getPassword()).matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$"))){
                                     System.out.println(String.valueOf(objPFpassword.getPassword()));

                 throw new Exception("Enter a valid password, A valid passowrd must contain atleast one lowercase, uppercase, special and digit character.And must be of length between 8-20"); 
                }
                else if(!(objTFPetName2.getText().matches("^[a-zA-Z]*$"))){
                 throw new Exception("Enter a valid pet name"); 
                }
                else{
                vic = new Victim();
                vic.setName(objTFName.getText());
                vic.setContact(Long.parseLong(objTFCNo.getText()));
                vic.setEmail(objTFEmail.getText());
                vic.setCity(CBTabVictimCity.getSelectedItem().toString());
                vic.setPassword(String.valueOf(objPFpassword.getPassword()));
                vic.setSecurity_question(objTFPetName2.getText());
                
                vicReg = new VictimRegistration(vic);
                
                objTFName.setText("");
                objTFCNo.setText("");
                objTFEmail.setText("");
                CBTabVictimCity.setSelectedItem("Select");
                objPFpassword.setText("");
                objTFPetName2.setText("");
                
                
                }
            }
            
        }
          catch(Exception e)
        {
          
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_btnTabVicRegActionPerformed

    private void CBTabStaffEntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBTabStaffEntMouseClicked
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_CBTabStaffEntMouseClicked

    private void CBTabStaffEntMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBTabStaffEntMouseExited
        // TODO add your handling code here:
         if(CBTabStaffEnt.getSelectedItem().toString()=="Hospital"){
             CBTabStaffDept.removeAllItems();
             CBTabStaffDept.addItem("Select");
           CBTabStaffDept.addItem("MANAGEMENT");
           CBTabStaffDept.addItem("COUNSELLING_DEPARTMENT");
           CBTabStaffDept.addItem("TEST_DEPARTMENT");
           
        }
         else if(CBTabStaffEnt.getSelectedItem().toString()=="Investigation"){
              CBTabStaffDept.removeAllItems();
              CBTabStaffDept.addItem("Select");
           CBTabStaffDept.addItem("HEAD_DEPARTMENT");
           CBTabStaffDept.addItem("INVESTIGATION_DEPARTMENT");
           }
         else if(CBTabStaffEnt.getSelectedItem().toString()=="Justice"){
              CBTabStaffDept.removeAllItems();
              CBTabStaffDept.addItem("Select");
           CBTabStaffDept.addItem("LAWYER_DEPARTMENT");
           CBTabStaffDept.addItem("JUDGE_DEPARTMENT");
           }
         else if(CBTabStaffEnt.getSelectedItem().toString()=="Raise Your Voice") {
              CBTabStaffDept.removeAllItems();
              CBTabStaffDept.addItem("Select");
           CBTabStaffDept.addItem("ADMINISTRATION");
           }
         
    }//GEN-LAST:event_CBTabStaffEntMouseExited

    private void CBTabStaffDeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBTabStaffDeptMouseExited
        // TODO add your handling code here:
        if(CBTabStaffDept.getSelectedItem().toString()=="MANAGEMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Manager");
           
        }
         else if(CBTabStaffDept.getSelectedItem().toString()=="INVESTIGATION_DEPARTMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Investigator");
           }
          else if(CBTabStaffDept.getSelectedItem().toString()=="HEAD_DEPARTMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Superintendent");
           }
         else if(CBTabStaffDept.getSelectedItem().toString()=="COUNSELLING_DEPARTMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Counsellor");
           
           }
         else if(CBTabStaffDept.getSelectedItem().toString()=="TEST_DEPARTMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Collector");
           CBTabStaffRole.addItem("Assistant");
           }
         else if(CBTabStaffDept.getSelectedItem().toString()=="LAWYER_DEPARTMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Lawyer");
           }
         else if(CBTabStaffDept.getSelectedItem().toString()=="JUDGE_DEPARTMENT"){
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Judge");
           }
         else if(CBTabStaffDept.getSelectedItem().toString()=="ADMINISTRATION") {
             CBTabStaffRole.removeAllItems();
              CBTabStaffRole.addItem("Select");
           CBTabStaffRole.addItem("Admin");
           }
    }//GEN-LAST:event_CBTabStaffDeptMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainRegister().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBTabStaffCity;
    private javax.swing.JComboBox<String> CBTabStaffDept;
    private javax.swing.JComboBox<String> CBTabStaffEnt;
    private javax.swing.JComboBox<String> CBTabStaffRole;
    private javax.swing.JComboBox<String> CBTabVictimCity;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStaffReg;
    private javax.swing.JButton btnTabStaffReg;
    private javax.swing.JButton btnTabVicReg;
    private javax.swing.JButton btnVictimReg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField objPFpassword;
    private javax.swing.JPasswordField objPFpassword2;
    private javax.swing.JTextField objTFCNo;
    private javax.swing.JTextField objTFCNo1;
    private javax.swing.JTextField objTFEmail;
    private javax.swing.JTextField objTFEmail1;
    private javax.swing.JTextField objTFName;
    private javax.swing.JTextField objTFName1;
    private javax.swing.JTextField objTFPetName1;
    private javax.swing.JTextField objTFPetName2;
    private javax.swing.JPanel pnlLeftReg;
    private javax.swing.JPanel pnlMainReg;
    private javax.swing.JPanel pnlTabFirst;
    private javax.swing.JPanel pnlTabStaffReg;
    private javax.swing.JPanel pnlTabVictimReg;
    private javax.swing.JPanel pnlTopReg;
    // End of variables declaration//GEN-END:variables
}
