/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Service.Constants;
import Service.DBConnection;
import Service.InvestigationRequest;
import Service.MedicalRequest;
import Service.RequestInvestigation;
import Service.RequestMedical;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mahak
 */
public class VictimReporting extends javax.swing.JFrame {

    /**
     * Creates new form VictimReporting
     */
    RequestInvestigation reqInv;
    InvestigationRequest invRequest;
    MedicalRequest medReq;
    RequestMedical reqMed;
    String vicEmail;
    String vicPass;
    
    DBConnection DBcon = new DBConnection();
       
        Connection con= DBcon.getDbcon();
//    public VictimReporting() {
//        initComponents();
//    }

    public VictimReporting(String vicEmail,String vicPass) {
        initComponents();
        this.vicEmail = vicEmail;
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlMainVictimRep = new javax.swing.JPanel();
        pnlLeftVictimRep = new javax.swing.JPanel();
        lblRequest = new javax.swing.JLabel();
        btnStatus = new javax.swing.JButton();
        btnInvestigation = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        btnMedFacility = new javax.swing.JButton();
        pnlRightVictimRep = new javax.swing.JPanel();
        pnlTopVictimRep = new javax.swing.JPanel();
        lblCloseLogin1 = new javax.swing.JLabel();
        lblTop = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        pnlTabPane1 = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        pnlTabPaneInvestigate = new javax.swing.JPanel();
        lblCulpritName = new javax.swing.JLabel();
        TFCulpritName = new javax.swing.JTextField();
        lblCrimeDesc = new javax.swing.JLabel();
        lblCulpritPic = new javax.swing.JLabel();
        TFCrimeLoc = new javax.swing.JTextField();
        TxtAreaCrimeDesc = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblCrimeLoc = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblCrimeDate = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlTabPaneMedical = new javax.swing.JPanel();
        lblProbDesc = new javax.swing.JLabel();
        TxtAreaProbDesc = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblAge = new javax.swing.JLabel();
        btnSubmitMedical = new javax.swing.JButton();
        lblService = new javax.swing.JLabel();
        TFAge = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        CBService = new javax.swing.JComboBox<>();
        CBGender = new javax.swing.JComboBox<>();
        pnlTabPaneStatus = new javax.swing.JPanel();
        tblInvestigation = new javax.swing.JScrollPane();
        jInvestigationTable = new javax.swing.JTable();
        tblMedical = new javax.swing.JScrollPane();
        jMedicalTable = new javax.swing.JTable();
        btnProvideConsent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        pnlMainVictimRep.setBackground(new java.awt.Color(255, 255, 255));

        pnlLeftVictimRep.setBackground(new java.awt.Color(68, 168, 217));
        pnlLeftVictimRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRequest.setFont(lblRequest.getFont().deriveFont(lblRequest.getFont().getSize()+25f));
        lblRequest.setForeground(new java.awt.Color(255, 255, 255));
        lblRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequest.setText("Request");
        pnlLeftVictimRep.add(lblRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 102, 207, 68));

        btnStatus.setBackground(new java.awt.Color(255, 255, 255));
        btnStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStatus.setText("Status");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        pnlLeftVictimRep.add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 265, 60));

        btnInvestigation.setBackground(new java.awt.Color(255, 255, 255));
        btnInvestigation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInvestigation.setText("Investigation");
        btnInvestigation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestigationActionPerformed(evt);
            }
        });
        pnlLeftVictimRep.add(btnInvestigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 265, 60));

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        pnlLeftVictimRep.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));

        btnMedFacility.setBackground(new java.awt.Color(255, 255, 255));
        btnMedFacility.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMedFacility.setText("Medical Facility");
        btnMedFacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedFacilityActionPerformed(evt);
            }
        });
        pnlLeftVictimRep.add(btnMedFacility, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 265, 60));

        pnlRightVictimRep.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightVictimRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTopVictimRep.setBackground(new java.awt.Color(255, 255, 255));
        pnlTopVictimRep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCloseLogin1.setBackground(new java.awt.Color(68, 168, 217));
        lblCloseLogin1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCloseLogin1.setForeground(new java.awt.Color(68, 168, 217));
        lblCloseLogin1.setText("X");
        lblCloseLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseLogin1MouseClicked(evt);
            }
        });
        pnlTopVictimRep.add(lblCloseLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 20, 20));

        lblTop.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTop.setForeground(new java.awt.Color(68, 168, 217));
        lblTop.setText("Take Your First Step");
        pnlTopVictimRep.add(lblTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 430, 50));

        pnlRightVictimRep.add(pnlTopVictimRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        pnlTabPane1.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/help1.jpg"))); // NOI18N
        pnlTabPane1.add(lblHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 620, 520));

        jTabbedPane.addTab("", pnlTabPane1);

        pnlTabPaneInvestigate.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabPaneInvestigate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCulpritName.setBackground(new java.awt.Color(0, 0, 0));
        lblCulpritName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCulpritName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCulpritName.setText(" Culprit Name:");
        pnlTabPaneInvestigate.add(lblCulpritName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 110, 35));
        pnlTabPaneInvestigate.add(TFCulpritName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 224, 35));

        lblCrimeDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrimeDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCrimeDesc.setText("Crime Description:");
        pnlTabPaneInvestigate.add(lblCrimeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 27));

        lblCulpritPic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCulpritPic.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCulpritPic.setText("Culprit Picture:");
        pnlTabPaneInvestigate.add(lblCulpritPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 102, 28));

        TFCrimeLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCrimeLocActionPerformed(evt);
            }
        });
        pnlTabPaneInvestigate.add(TFCrimeLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 224, 35));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(224, 74));
        TxtAreaCrimeDesc.setViewportView(jTextArea1);

        pnlTabPaneInvestigate.add(TxtAreaCrimeDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 360, 150));

        jLabel2.setText("Keep it Null if unknown");
        pnlTabPaneInvestigate.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 210, 20));

        lblCrimeLoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrimeLoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCrimeLoc.setText("Crime Location:");
        pnlTabPaneInvestigate.add(lblCrimeLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 102, 28));
        pnlTabPaneInvestigate.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 240, 35));

        lblCrimeDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrimeDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCrimeDate.setText("Crime Date:");
        pnlTabPaneInvestigate.add(lblCrimeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 102, 28));
        pnlTabPaneInvestigate.add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 500, 250));

        btnSubmit.setBackground(new java.awt.Color(255, 153, 51));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlTabPaneInvestigate.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, 140, 50));

        jLabel3.setText("Keep it Null if unknown");
        pnlTabPaneInvestigate.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 210, 20));

        jTabbedPane.addTab("", pnlTabPaneInvestigate);

        pnlTabPaneMedical.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabPaneMedical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProbDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProbDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProbDesc.setText("Problem Description:");
        pnlTabPaneMedical.add(lblProbDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 27));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setPreferredSize(new java.awt.Dimension(224, 74));
        TxtAreaProbDesc.setViewportView(jTextArea2);

        pnlTabPaneMedical.add(TxtAreaProbDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 310, 130));

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");
        pnlTabPaneMedical.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 102, 28));

        btnSubmitMedical.setBackground(new java.awt.Color(255, 153, 51));
        btnSubmitMedical.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmitMedical.setText("Submit");
        btnSubmitMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMedicalActionPerformed(evt);
            }
        });
        pnlTabPaneMedical.add(btnSubmitMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 130, 60));

        lblService.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblService.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblService.setText("Service:");
        pnlTabPaneMedical.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 102, 28));
        pnlTabPaneMedical.add(TFAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, 40));

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");
        pnlTabPaneMedical.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 102, 28));

        CBService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Counseling" }));
        pnlTabPaneMedical.add(CBService, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 200, 40));

        CBGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        pnlTabPaneMedical.add(CBGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 200, 40));

        jTabbedPane.addTab("", pnlTabPaneMedical);

        pnlTabPaneStatus.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabPaneStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInvestigationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInvestigation.setViewportView(jInvestigationTable);
        if (jInvestigationTable.getColumnModel().getColumnCount() > 0) {
            jInvestigationTable.getColumnModel().getColumn(1).setResizable(false);
            jInvestigationTable.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlTabPaneStatus.add(tblInvestigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 290));

        jMedicalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedical.setViewportView(jMedicalTable);
        if (jMedicalTable.getColumnModel().getColumnCount() > 0) {
            jMedicalTable.getColumnModel().getColumn(0).setResizable(false);
            jMedicalTable.getColumnModel().getColumn(1).setResizable(false);
            jMedicalTable.getColumnModel().getColumn(2).setResizable(false);
            jMedicalTable.getColumnModel().getColumn(3).setResizable(false);
            jMedicalTable.getColumnModel().getColumn(4).setResizable(false);
        }

        pnlTabPaneStatus.add(tblMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 290));

        btnProvideConsent.setBackground(new java.awt.Color(255, 153, 51));
        btnProvideConsent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProvideConsent.setText("Provide Consent");
        btnProvideConsent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProvideConsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvideConsentActionPerformed(evt);
            }
        });
        pnlTabPaneStatus.add(btnProvideConsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 170, 38));

        jTabbedPane.addTab("tab4", pnlTabPaneStatus);

        pnlRightVictimRep.add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 1205, 796));

        javax.swing.GroupLayout pnlMainVictimRepLayout = new javax.swing.GroupLayout(pnlMainVictimRep);
        pnlMainVictimRep.setLayout(pnlMainVictimRepLayout);
        pnlMainVictimRepLayout.setHorizontalGroup(
            pnlMainVictimRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainVictimRepLayout.createSequentialGroup()
                .addComponent(pnlLeftVictimRep, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRightVictimRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMainVictimRepLayout.setVerticalGroup(
            pnlMainVictimRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeftVictimRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRightVictimRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainVictimRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainVictimRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Boolean victimConsent(String requestId, String consent)
    {
        if(requestId==null)
            return null;
        
        DBConnection DBcon = new DBConnection();
        System.out.println("-------------Logging In-------------");
        Connection con= DBcon.getDbcon();
        String query = "UPDATE " + Constants.investigationTableName + " SET Status=? WHERE Request_Id=?";
        if(query.isBlank() || query.isEmpty())
            return null;
        
        try{
            PreparedStatement s = con.prepareStatement(query);
            s.setString(1, consent);
            s.setString(2, requestId);
            System.out.println("-------------Updating Request Status in " + Constants.investigationTableName + "------------");
            Integer r = s.executeUpdate();
            System.out.println("-------------Query Executed------------");
            if(r == null)
            {
                JOptionPane.showMessageDialog( null, "Some error occured. Status update unsucccessfull. Please try after sometime.");
            }
            s.close();
            con.close();
            return true;
        }
        catch (SQLException e1)
        {
            JOptionPane.showMessageDialog( null, "Some error occured. Status update unsucccessfull. Please try after sometime.");
        }
        return null;
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //new HospitalAdmin().setVisible(true);
            try
        {   
          
            if(jTextArea1.getText().isEmpty()){
                     throw new Exception("Add crime description"); 
             }
            else if(TFCrimeLoc.getText().isEmpty())
            {
                 throw new Exception("Add crime location"); 
            }
            else if(String.valueOf(jDateChooser1.getDate()).isEmpty()){
                     throw new Exception("Select crime date"); 
             }
            
            else{  invRequest = new InvestigationRequest(); 
                    invRequest.setVictim_email(vicEmail);
                    invRequest.setCulprit_Name(TFCulpritName.getText());
                    invRequest.setCrime_Description(jTextArea1.getText());
                    invRequest.setCrime_Location(TFCrimeLoc.getText());
                    invRequest.setCrime_Date(String.valueOf(jDateChooser1.getDate()));
                    invRequest.setCulprit_Image(String.valueOf(jFileChooser1.getName()));
                    invRequest.setDepartment("Head Department");
                    invRequest.setAssigned_To(" ");
                    invRequest.setStatus("Submitted");
                    invRequest.setRequest_Date("5/2/2022");
                    invRequest.setNotes(" ");
                    invRequest.setUpdate_Date(" ");
                    invRequest.setTest_Assigne(" ");
                reqInv = new RequestInvestigation();
                reqInv.ReqInvestigation(invRequest);
                    //JOptionPane.showMessageDialog(null,"Request raised");
                   }
                    

        }
          catch(Exception e)
        {
          
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMedicalActionPerformed
        // TODO add your handling code here:
            try
        {   
          
            if(jTextArea2.getText().isEmpty()){
                     throw new Exception("Add problem description"); 
             }
            else if(String.valueOf(CBService.getSelectedItem())=="Select")
            {
                 throw new Exception("Select service"); 
            }
            else if(String.valueOf(CBGender.getSelectedItem())=="Select"){
                     throw new Exception("Select gender"); 
             }
            else if(TFAge.getText().isEmpty()){
                     throw new Exception("Add age"); 
             }
            else{  medReq = new MedicalRequest(); 
                    medReq.setVictim_email(vicEmail);
                    medReq.setProblem_Description(jTextArea2.getText());
                    medReq.setService(String.valueOf(CBService.getSelectedItem()));
                     medReq.setGender(String.valueOf(CBGender.getSelectedItem()));
                  medReq.setDepartment(" ");
                    medReq.setAssigned_To(" ");
                    medReq.setStatus("Submitted");
                    medReq.setRequest_Date("5/2/2022");
                    medReq.setNotes(" ");
                    medReq.setUpdate_Date(" ");
                reqMed = new RequestMedical(medReq);
                
                   // JOptionPane.showMessageDialog(null,"Request raised");
                    
                   }
                    

        }
          catch(Exception e)
        {
          e.printStackTrace();
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
    }//GEN-LAST:event_btnSubmitMedicalActionPerformed

    private void btnInvestigationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvestigationActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnInvestigationActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
         populateMedicalTable();
         populateInvestigatioTable();
           jTabbedPane.setSelectedIndex(3);
       
    }//GEN-LAST:event_btnStatusActionPerformed

    private void TFCrimeLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCrimeLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCrimeLocActionPerformed

    private void lblCloseLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseLogin1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseLogin1MouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Successfully Logout");
        new HomePage().setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnMedFacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedFacilityActionPerformed
        // TODO add your handling code here:
         jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_btnMedFacilityActionPerformed

    private void btnProvideConsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvideConsentActionPerformed

        DefaultTableModel model = (DefaultTableModel) jInvestigationTable.getModel();
        int selectedRowIndex = jInvestigationTable.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        String requestId = String.valueOf(model.getValueAt(selectedRowIndex, 0));
        Boolean response = victimConsent(requestId, "CONSENT_PROVIDED");
        if(response != false)
        {
            JOptionPane.showMessageDialog(null, "Successfully provided consent");
        }
    }//GEN-LAST:event_btnProvideConsentActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VictimReporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VictimReporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VictimReporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VictimReporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VictimReporting().setVisible(true);
//            }
//        });
//    }
 public void populateInvestigatioTable(){
      System.out.println("-------------Fetching Investigation Request-------------");
          try 
  {
      
    PreparedStatement stmt=con.prepareStatement("Select REQUEST_ID, VICTIM_EMAIL, DEPARTMENT, ASSIGNED_TO,STATUS from INVESTIGATION_REQUEST where VICTIM_EMAIL=?");
                stmt.setString(1,vicEmail);
                ResultSet rset=stmt.executeQuery();
                System.out.println("query executed");
                    
//      String columns[] = { "REQUEST_ID", "VICTIM_EMAIL", "DEPARTMENT", "ASSIGNED_TO","STATUS" };
//      String data[][] = new String[100][5];
//         
        
        DefaultTableModel model = (DefaultTableModel) jInvestigationTable.getModel();
        model.setRowCount(0);
     Object[] row = new Object[5];
     
      while (rset.next()) {
           if(rset.getString("VICTIM_EMAIL").isEmpty()){
              System.out.println("");
          }
          else{
        int req_id = rset.getInt("REQUEST_ID");
        String email = rset.getString("VICTIM_EMAIL");
        String dept = rset.getString("DEPARTMENT");
        String assigned_to = rset.getString("ASSIGNED_TO");
        String status = rset.getString("STATUS");
        
         row[0]= req_id;
            row[1]= email;
            row[2]= dept;
            row[3]= assigned_to;
            row[4]= status;
            model.addRow(row);
        
      }    
      }
                                    
    
    
    } catch(Exception e) {
              System.out.println("Exception handled");
    }

 }
  public void populateMedicalTable(){
      System.out.println("-------------Fetching Medical Request-------------");
          try 
  {
      
    PreparedStatement stmt=con.prepareStatement("Select REQUEST_ID, VICTIM_EMAIL, DEPARTMENT, ASSIGNED_TO,STATUS from MEDICAL_REQUEST where VICTIM_EMAIL=?");
                stmt.setString(1,vicEmail);
                ResultSet rset=stmt.executeQuery();
                System.out.println("query executed");
                    
//      String columns[] = { "REQUEST_ID", "VICTIM_EMAIL", "DEPARTMENT", "ASSIGNED_TO","STATUS" };
//      String data[][] = new String[100][5];
//         
                 
        DefaultTableModel model = (DefaultTableModel) jMedicalTable.getModel();
        model.setRowCount(0);
     Object[] row = new Object[5];
     
      while (rset.next()) {
          if(rset.getString("VICTIM_EMAIL").isEmpty()){
              System.out.println("");
          }
          else{
        int req_id = rset.getInt("REQUEST_ID");
        String email = rset.getString("VICTIM_EMAIL");
        String dept = rset.getString("DEPARTMENT");
        String assigned_to = rset.getString("ASSIGNED_TO");
        String status = rset.getString("STATUS");
        
         row[0]= req_id;
            row[1]= email;
            row[2]= dept;
            row[3]= assigned_to;
            row[4]= status;
            model.addRow(row);
        
      }  }                 
                                    
    
    
    } catch(Exception e) {
              System.out.println("Exception handled");
    }
          

 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBGender;
    private javax.swing.JComboBox<String> CBService;
    private javax.swing.JTextField TFAge;
    private javax.swing.JTextField TFCrimeLoc;
    private javax.swing.JTextField TFCulpritName;
    private javax.swing.JScrollPane TxtAreaCrimeDesc;
    private javax.swing.JScrollPane TxtAreaProbDesc;
    private javax.swing.JButton btnInvestigation;
    private javax.swing.JButton btnMedFacility;
    private javax.swing.JButton btnProvideConsent;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitMedical;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTable jInvestigationTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jMedicalTable;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCloseLogin1;
    private javax.swing.JLabel lblCrimeDate;
    private javax.swing.JLabel lblCrimeDesc;
    private javax.swing.JLabel lblCrimeLoc;
    private javax.swing.JLabel lblCulpritName;
    private javax.swing.JLabel lblCulpritPic;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblProbDesc;
    private javax.swing.JLabel lblRequest;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblTop;
    private javax.swing.JPanel pnlLeftVictimRep;
    private javax.swing.JPanel pnlMainVictimRep;
    private javax.swing.JPanel pnlRightVictimRep;
    private javax.swing.JPanel pnlTabPane1;
    private javax.swing.JPanel pnlTabPaneInvestigate;
    private javax.swing.JPanel pnlTabPaneMedical;
    private javax.swing.JPanel pnlTabPaneStatus;
    private javax.swing.JPanel pnlTopVictimRep;
    private javax.swing.JScrollPane tblInvestigation;
    private javax.swing.JScrollPane tblMedical;
    // End of variables declaration//GEN-END:variables
}
